### ISSUE TITLE
questions about training time

### ISSUE THREAD

**Issue by feixh** [hustvl/GaussianDreamer#6]
hi there,

In Figure 1 of your paper, you mentioned that training of DreamFusion takes more than 8 hours, and Magic3D takes more than 5 hours. But DreamFusion mentioned that their training time is about 1.5 hours, and Magic3D about 40 minutes. Why your reported training time of other approaches are much longer?

**Comment by taoranyi** [comment]
Thank Thank for your attention. When we mention GPU time in our paper, it is because DreamFusion and magic3D adopt multi-GPU training, so the GPU time is the time reported multiplied by the number of GPUs. For more details, you can refer to magic3D.
![1111](https://github.com/hustvl/GaussianDreamer/assets/64740876/602dd665-3e8a-47b6-96a5-1f18436e72e2)
![2222](https://github.com/hustvl/GaussianDreamer/assets/64740876/5b481607-19a8-4c44-a361-4fcf7369247e)
